const styles = `
  :root{font-family:ui-sans-serif,system-ui,sans-serif;color:#eaf2ff;background:#07101d;color-scheme:dark}
  *{box-sizing:border-box}body{margin:0}main{max-width:860px;margin:auto;padding:64px 24px}
  a{color:#77c7ff}h1{font-size:clamp(2rem,6vw,4.5rem);line-height:1;margin:.3em 0}h2{margin-top:2rem}
  p,li{color:#b8c8db;line-height:1.65}.pill{display:inline-block;border:1px solid #34506f;border-radius:999px;padding:6px 10px;color:#8ed5ff}
  .card{background:#0e1c2d;border:1px solid #263f5e;border-radius:16px;padding:20px;margin:18px 0}code{color:#b7e0ff}
`;

function page(title, body) {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title><style>${styles}</style></head><body><main>${body}</main></body></html>`;
}

export function landingPage(baseUrl) {
  return page("OpsTruth", `<span class="pill">Evidence-first verification</span><h1>Know what the code proves.</h1><p>OpsTruth gives ChatGPT and Codex live, read-only verification tools for public GitHub repositories. Evidence Graph v1 binds repositories, commits, CI, runtime observations and execution receipts to exact subjects, preserves contradictions and returns portable signed snapshots without changing the target project.</p><div class="card"><strong>MCP endpoint</strong><p><code>${baseUrl}/mcp</code></p><p>19 read-only tools · 6 workflow skills · signed snapshots and receipts · deterministic state deltas</p></div><p><a href="/signing-key">Signing key</a> · <a href="/privacy">Privacy</a> · <a href="/terms">Terms</a> · <a href="/support">Support</a> · <a href="https://github.com/AyobamiH/opstruth-chatgpt-plugin">GitHub</a></p>`);
}

export function privacyPage() {
  return page("Privacy | OpsTruth", `<span class="pill">Privacy</span><h1>Privacy policy</h1><p>Effective 27 August 2026. OpsTruth is published by AYOBAMI JOHN HAASTRUP.</p><h2>Data processed</h2><p>The public MCP service receives the public GitHub repository identifier, public HTTPS health URL, caller-held evidence snapshots and protocol artifacts that a user deliberately submits. It fetches bounded public repository, CI and response-header evidence to produce the requested report.</p><h2>Data minimisation</h2><p>The service does not accept private-repository credentials, user tokens or secret values. Environment files and key files are not opened. Secret-like findings are returned only as redacted types and locations. Deployment response bodies are not retained.</p><h2>Aggregate usage analytics</h2><p>For reliability and product improvement, Cloudflare Analytics Engine receives bounded aggregate fields only: tool, outcome, verdict, capped evidence and gap counts, CI and deployment-probe flags, signing status, rounded latency, plugin version and coarse client family. Optional feedback records one controlled reason code and surface. Prompts, repository names, URLs, IP addresses, graph contents, receipts, free text and stable user identifiers are not recorded.</p><h2>Storage</h2><p>OpsTruth does not create user accounts or persist user reports, snapshots or evidence graphs. Portable snapshots are returned to the caller. Cloudflare and GitHub may process standard request metadata under their own terms. Public GitHub responses may be cached briefly to protect availability and rate limits.</p><h2>Evidence signing</h2><p>Reports and Evidence Graph snapshots may include an Ed25519 signature generated with a Cloudflare Worker secret. The public verification key and fingerprint are returned so integrity and signer trust can be checked independently. Signature validity does not prove that an executor was authorised or that its claimed outcome occurred.</p><h2>Purpose and sharing</h2><p>Data is processed only to provide repository verification, maintain service reliability and improve the tool. It is not sold or used for advertising.</p><h2>Your choices</h2><p>Submit only public repositories, public HTTPS endpoints and protocol artifacts you are comfortable asking the service to inspect. Feedback is optional. For questions, use the <a href="/support">support page</a>.</p>`);
}

export function termsPage() {
  return page("Terms | OpsTruth", `<span class="pill">Terms</span><h1>Terms of service</h1><p>Effective 25 August 2026.</p><p>OpsTruth provides read-only static, public CI and bounded HTTPS health observations. Reports and signatures are evidence aids, not guarantees of correctness, security, legal compliance, deployability or broader runtime behavior.</p><p>Do not use the service to submit credentials, private source code, personal data or repositories and endpoints you are not authorised to inspect. Do not attempt to bypass GitHub access controls, network boundaries or service limits.</p><p>The public tools do not execute repository code or change repositories, databases, CI systems or cloud providers. Sandbox execution requires a separate authenticated runner, isolated environment and explicit user approval.</p><p>The service is provided without warranty. Verify important findings independently before acting.</p>`);
}

export function supportPage() {
  return page("Support | OpsTruth", `<span class="pill">Support</span><h1>OpsTruth support</h1><p>For incorrect evidence, false positives, connection problems or documentation issues, open a redacted report in <a href="https://github.com/AyobamiH/opstruth-chatgpt-plugin/issues/new">GitHub Issues</a>.</p><p>Include the repository URL, tool name, expected result and the smallest safe evidence excerpt. Never include tokens, private keys, customer data or private source code.</p><p>For sensitive security reports, use GitHub private vulnerability reporting when available. Otherwise request a private channel without posting the sensitive details.</p>`);
}
